### ISSUE TITLE
Numpy crash in BLOAD with numpy 1.11

### ISSUE THREAD

**Issue by robhagemans** [robhagemans/pcbasic#51]
A crash occurs in tests `BLOAD` and `BLOAD-tandy` with numpy 1.11.0 (newer version than before?)
See below. This occurs in the `BLOAD` statement on version 15.08.11 when using the pygame interface. Unclear if it occurs in 16.12, as the tests may not exercise this code in that version.

```
Running test BLOAD/... ERROR: Traceback (most recent call last):
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/run.py", line 66, in run_once
    if not statements.parse_statement():
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/statements.py", line 164, in parse_statement
    elif c == tk.BLOAD:     exec_bload(ins)
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/statements.py", line 644, in exec_bload
    machine.bload(f, offset)
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/machine.py", line 226, in bload
    set_memory_block(addr, buf)
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/machine.py", line 354, in set_memory_block
    set_video_memory_block(addr, buf[:video_len])
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/machine.py", line 536, in set_video_memory_block
    state.console_state.screen.mode.set_memory(addr, some_bytes)
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/modes.py", line 688, in set_memory
    bytes_to_interval(bytes[ofs:ofs+length], self.ppb))
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/backend.py", line 1362, in put_interval
    video.put_interval(pagenum, x, y, colours, mask)
  File "/home/rob/Projects/basic-project/branch1508/pcbasic/video_pygame.py", line 1272, in put_interval
    ref |= colours
TypeError: ufunc 'bitwise_or' output (typecode 'l') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''

```

**Comment by robhagemans** [comment]
Does not seem to occur in 16.12. Fixed by commit 60b0199 in 15.08
