### ISSUE TITLE
pcbasic crash

### ISSUE THREAD

**Issue by udhos** [robhagemans/pcbasic#90]
This code is crashing pcbasic:

```
lab@ubu1:~$ more a.bas
100 IF X > Y THEN PRINT "GREATER" ELSE IF Y > X THEN&
110 PRINT "LESS THAN"
200 ELSE PRINT "EQUAL"
lab@ubu1:~$

```

Command line is:

`lab@ubu1:~$ ./.local/bin/pcbasic a.bas`

Head of crash log is:

```
lab@ubu1:~$ more /home/lab/.local/share/pcbasic-2.0/crash-20181217-xTv6iW.log
PC-BASIC crash log
====================================================================================================
FATAL ERROR
version   2.0.1
python    2.7.15rc1 [64bit ]
platform  Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic
interface VideoCurses, AudioPlugin
statement :LOAD "@:#C47CE58"

program.py:365, merge
tokeniser.py:123, tokenise_line
tokeniser.py:281, tokenise_number
numbers.py:271, from_oct
ValueError: invalid literal for int() with base 8: ''

This is a bug in PC-BASIC.
Sorry about that. To help improve PC-BASIC, please file a bug report at
  https://github.com/robhagemans/pcbasic/issues
Please include the messages above and as much information as you can about what you were doing and how this happened. Please attach the log file
  /home/lab/.local/share/pcbasic-2.0/crash-20181217-xTv6iW.log
Thank you!

Press a key to close this window.
Traceback (most recent call last):
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/guard.py", line 48, in protect
    yield
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/main.py", line 107, in run_session
    session.execute(b'LOAD "%s"' % (progfile,))
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/basic/api.py", line 86, in execute
    self._impl.execute(cmd)
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/basic/implementation.py", line 252, in execute
    self.interpreter.loop()
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/basic/interpreter.py", line 124, in loop
    self.parse()
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/basic/interpreter.py", line 113, in parse
    self.parser.parse_statement(ins)
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/basic/parser/statements.py", line 86, in parse_statement
    self._callbacks[c](parse_args(ins))
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/basic/implementation.py", line 562, in load_
    self.program.load(f)
  File "/home/lab/.local/lib/python2.7/site-packages/pcbasic/basic/program.py", line 347, in load
    self.merge(g)

```

**Comment by robhagemans** [comment]
Thanks for reporting! Fixed by commit 15172918
